export const data = [
  {
    name: "Sharyl Vondrasek",
    email: "svondrasek0@google.it",
    created_date: "2024/06/11",
    role: "Construction Worker",
  },
  {
    name: "Jaquith Karpman",
    email: "jkarpman1@weather.com",
    created_date: "2024/11/29",
    role: "Estimator",
  },
  {
    name: "Guenevere Nials",
    email: "gnials2@privacy.gov.au",
    created_date: "2024/12/15",
    role: "Surveyor",
  },
  {
    name: "Dennie Floweth",
    email: "dfloweth3@sourceforge.net",
    created_date: "2024/07/20",
    role: "Surveyor",
  },
  {
    name: "Saundra Joddins",
    email: "sjoddins4@indiatimes.com",
    created_date: "2024/04/21",
    role: "Construction Manager",
  },
  {
    name: "Berenice Knightly",
    email: "bknightly5@mysql.com",
    created_date: "2024/09/28",
    role: "Construction Manager",
  },
  {
    name: "Yovonnda Caccavella",
    email: "ycaccavella6@chron.com",
    created_date: "2024/10/28",
    role: "Construction Worker",
  },
  {
    name: "Billie Dogerty",
    email: "bdogerty7@ucoz.ru",
    created_date: "2024/06/01",
    role: "Estimator",
  },
  {
    name: "Kris Sheeran",
    email: "ksheeran8@twitpic.com",
    created_date: "2024/10/22",
    role: "Electrician",
  },
  {
    name: "Doti Giblin",
    email: "dgiblin9@samsung.com",
    created_date: "2024/05/03",
    role: "Estimator",
  },
  {
    name: "Jeanine Chadwen",
    email: "jchadwena@usa.gov",
    created_date: "2024/05/05",
    role: "Surveyor",
  },
  {
    name: "Mandie Serck",
    email: "mserckb@tuttocitta.it",
    created_date: "2024/04/06",
    role: "Construction Expeditor",
  },
  {
    name: "Joceline Grayne",
    email: "jgraynec@pbs.org",
    created_date: "2024/02/24",
    role: "Supervisor",
  },
  {
    name: "Hedwig Bawden",
    email: "hbawdend@godaddy.com",
    created_date: "2024/10/27",
    role: "Estimator",
  },
  {
    name: "Ned McGeachie",
    email: "nmcgeachiee@time.com",
    created_date: "2023/12/26",
    role: "Architect",
  },
  {
    name: "Brena Bromby",
    email: "bbrombyf@usda.gov",
    created_date: "2024/08/12",
    role: "Supervisor",
  },
  {
    name: "Indira Heppenspall",
    email: "iheppenspallg@psu.edu",
    created_date: "2024/01/22",
    role: "Engineer",
  },
  {
    name: "Hans Kisbee",
    email: "hkisbeeh@dion.ne.jp",
    created_date: "2024/01/30",
    role: "Subcontractor",
  },
  {
    name: "Maynord Lackner",
    email: "mlackneri@google.com.br",
    created_date: "2024/10/09",
    role: "Subcontractor",
  },
  { name: "Lucien Moens", email: "lmoensj@a8.net", created_date: "2023/12/28", role: "Architect" },
  {
    name: "Casar Gosnoll",
    email: "cgosnollk@fema.gov",
    created_date: "2024/08/07",
    role: "Engineer",
  },
  {
    name: "Pavel Letten",
    email: "plettenl@ifeng.com",
    created_date: "2024/01/14",
    role: "Project Manager",
  },
  {
    name: "Pearle Covotto",
    email: "pcovottom@google.de",
    created_date: "2024/12/19",
    role: "Project Manager",
  },
  {
    name: "Hildagarde Tibalt",
    email: "htibaltn@indiegogo.com",
    created_date: "2024/03/03",
    role: "Supervisor",
  },
  {
    name: "Aimee Landall",
    email: "alandallo@oracle.com",
    created_date: "2024/07/05",
    role: "Electrician",
  },
  {
    name: "Rem Newlands",
    email: "rnewlandsp@godaddy.com",
    created_date: "2024/02/14",
    role: "Architect",
  },
  {
    name: "Collie Simpson",
    email: "csimpsonq@narod.ru",
    created_date: "2024/09/16",
    role: "Construction Foreman",
  },
  {
    name: "Bryana O'Looney",
    email: "bolooneyr@fc2.com",
    created_date: "2024/05/27",
    role: "Supervisor",
  },
  {
    name: "Ethelin Bruckshaw",
    email: "ebruckshaws@gizmodo.com",
    created_date: "2024/08/30",
    role: "Electrician",
  },
  {
    name: "Dwain Filde",
    email: "dfildet@hugedomains.com",
    created_date: "2024/04/10",
    role: "Project Manager",
  },
  {
    name: "Enoch Ludgate",
    email: "eludgateu@goo.ne.jp",
    created_date: "2024/06/26",
    role: "Estimator",
  },
  {
    name: "Maud Thelwll",
    email: "mthelwllv@examiner.com",
    created_date: "2024/02/24",
    role: "Construction Worker",
  },
  {
    name: "Oralle Chadwin",
    email: "ochadwinw@cyberchimps.com",
    created_date: "2024/05/21",
    role: "Construction Foreman",
  },
  {
    name: "Rickie Aspenlon",
    email: "raspenlonx@t.co",
    created_date: "2024/08/19",
    role: "Project Manager",
  },
  {
    name: "Lari Vanyukov",
    email: "lvanyukovy@biblegateway.com",
    created_date: "2024/11/26",
    role: "Construction Manager",
  },
];
